services:
  - type: web
    name: api.e-commerce-store-lk
    region: frankfurt
    runtime: node
    autoDeploy: true
    plan: starter
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      npm start
    envVars:
      - fromGroup: e-commerce-store-lk

  - type: web
    name: app.e-commerce-store-lk
    runtime: static
    buildCommand: |
      cd frontend-lk
      npm install
      npm run build
    staticPublishPath: ./frontend-lk/dist
    envVars:
      - fromGroup: e-commerce-store-lk
