services:
  - type: web
    name: e-commerce-store-lk
    region: frankfurt
    runtime: node
    autoDeploy: true
    plan: starter
    buildCommand: |
      cd backend
      npm install
      cd ../frontend-lk
      npm install
      npm run build
    startCommand: |
      cd backend
      npm start
    envVars:
      - fromGroup: e-commerce-store-lk
