services:
  - type: web
    name: e-commerce-store-lk-api
    region: frankfurt
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      npm start
    envVars:
      - fromGroup: e-commerce-store-lk

  - type: web
    name: e-commerce-store-lk-app
    runtime: static
    buildCommand: |
      cd frontend-lk
      npm install
      npm run build
      pwd
    staticPublishPath: ./frontend-lk/dist
    envVars:
      - fromGroup: e-commerce-store-lk
