services:
  - type: web
    name: e-commerce-store-lk-api
    region: frankfurt
    runtime: node
    autoDeploy: true
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      npm start
    envVars:
      - fromGroup: e-commerce-store-lk

  - type: web
    name: e-commerce-store-lk-app
    runtime: static
    buildCommand: |
      cd frontend-lk 
      npm install
      npm run build
    staticPublishPath: ./dist
    envVars:
      - fromGroup: e-commerce-store-lk
